// World Info manipulation functions
export function addWorldInfoEntry(entry) {
    const newEntry = {
        key: entry.suggestedKeys.join(','),
        keysecondary: '',
        comment: `Auto-generated by DynamicLore`,
        content: entry.description,
        constant: false,
        selective: false
    };
    
    window.world_info.entries.push(newEntry);
    syncWorldInfo();
}

export function updateWorldInfoEntry(entry) {
    const existingEntry = window.world_info.entries.find(e => e.uid === entry.id);
    if (existingEntry) {
        existingEntry.content = entry.mergedContent;
        existingEntry.key = combineKeys(existingEntry.key, entry.suggestedKeys);
        syncWorldInfo();
    }
}

function combineKeys(existingKeys, newKeys) {
    const existing = existingKeys.split(',').map(k => k.trim());
    const combined = [...new Set([...existing, ...newKeys])];
    return combined.join(',');
}

function syncWorldInfo() {
    // Save world info and refresh UI
    console.log("World info updated");
}
